### ISSUE TITLE
[BUG]: vector-admin can not connect to postgres

### ISSUE THREAD

**Issue by chrislemke** [Mintplex-Labs/vector-admin#147]
### How are you running VectorAdmin?

Docker (remote machine)

### What happened?

Try to install vector-admin on an EC2 instance using the [Build docker image from source](https://github.com/Mintplex-Labs/vector-admin/blob/master/docker/DOCKER.md#build-docker-image-from-source) docs. I also followed the instruction form the [Common questions and fixes](https://github.com/Mintplex-Labs/vector-admin/blob/master/docker/DOCKER.md#common-questions-and-fixes) part.

But vector-admin can't connect to the postgres db:
```
Please make sure your database server is running at `host.docker.internal`:`5433`. PrismaClientInitializationError: 
Invalid `prisma.system_settings.create()` invocation:

Can't reach database server at `host.docker.internal`:`5433`

Please make sure your database server is running at `host.docker.internal`:`5433`.
    at wn.handleRequestError (/app/backend/node_modules/@prisma/client/runtime/library.js:123:7003)
    at wn.handleAndLogRequestError (/app/backend/node_modules/@prisma/client/runtime/library.js:123:6119)
    at wn.request (/app/backend/node_modules/@prisma/client/runtime/library.js:123:5839)
    at async l (/app/backend/node_modules/@prisma/client/runtime/library.js:128:9763)
    at async Object.updateSettings (/app/backend/models/systemSettings.js:45:25)
    at async Object.setUid (/app/backend/models/telemetry.js:63:5)
    at async Object.findOrCreateId (/app/backend/models/telemetry.js:69:19)
    at async setupTelemetry (/app/backend/utils/boot/index.js:37:3)
    at async systemInit (/app/backend/utils/boot/index.js:47:5)
    at async Server.<anonymous> (/app/backend/index.js:62:5) {
  clientVersion: '5.3.1',
  errorCode: undefined
}
Backend server listening on port 3001
Error: getaddrinfo ENOTFOUND host.docker.internal
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'host.docker.internal'
}
```

Also tried various combinations of different ports, using localhost, etc. Any idea what I am doing wrong? Thanks in advance!

**Comment by chrislemke** [comment]
Fixed it: using `DATABASE_CONNECTION_STRING="postgresql://vectoradmin:password@postgres:5432/vdbms"`
