### ISSUE TITLE
The table `public.system_settings` does not exist in the current database , when following How to get started (Development environment)

### ISSUE THREAD

**Issue by sglebs** [Mintplex-Labs/vector-admin#83]
Following the steps in https://github.com/Mintplex-Labs/vector-admin#how-to-get-started-development-environment , when I try the step 

````
yarn dev:server
```

I get the error:

```
The table `public.system_settings` does not exist in the current database.
    at wn.handleRequestError (/Users/mqm/git/oc/vector-admin/backend/node_modules/@prisma/client/runtime/library.js:123:6730)
    at wn.handleAndLogRequestError (/Users/mqm/git/oc/vector-admin/backend/node_modules/@prisma/client/runtime/library.js:123:6119)
    at wn.request (/Users/mqm/git/oc/vector-admin/backend/node_modules/@prisma/client/runtime/library.js:123:5839)
    at async l (/Users/mqm/git/oc/vector-admin/backend/node_modules/@prisma/client/runtime/library.js:128:9763)
    at async Object.updateSettings (/Users/mqm/git/oc/vector-admin/backend/models/systemSettings.js:45:25)
    at async saveDebug (/Users/mqm/git/oc/vector-admin/backend/utils/debug/index.js:19:3) {
  code: 'P2021',
  clientVersion: '5.3.1',
  meta: { table: 'public.system_settings' }
}

```


Shouldn't the tables be created on first run?

**Comment by timothycarambat** [comment]
Run `yarn prisma:setup` from project root. We dont migrate on boot because when working in development you may accidentally migrate a schema that is currently being worked on. So migrations are deliberately handled during development.

**Comment by sglebs** [comment]
My humble suggestion: perhaps update the documentation? Right here:

```
In separate terminal windows from project root:
```

Just add, perhaps as a sub-bullet of "yarn dev:server", something like: "Make sure you first run "yarn prisma:setup" to initialize your local, empty database".

Just a suggestion. Thanks for listening.
