### ISSUE TITLE
yarn dev:setup produces "vector-admin/backend/node_modules/@prisma/engines: Command failed."

### ISSUE THREAD

**Issue by mjackstewart** [Mintplex-Labs/vector-admin#87]
Hello!

I'm attempting to setup vector-admin on an Ubuntu VM running on WSL 2.

This is the Ubuntu release information:

Distributor ID: Ubuntu 
Description:    Ubuntu 22.04.3 LTS 
Release:        22.04 
Codename:       jammy

I installed the most recent version of yarn with this command:

sudo apt install yarn

This also installed nodejs.

So far I've had two problems with the very first command, yarn dev:setup:

- The first was the error:

yarn run v1.22.19 error vector-data-management-system@0.0.2: The engine "node" is incompatible with this module. Expected version ">=18".  Got "12.22.9" error Commands cannot run with an incompatible environment. i

I was able to deal with that by issuing this command:

yarn config set ignore-engines  true

- The installer ran, but experienced this error toward the end of the installation:

error /mnt/c/Development/Projects/Python/vectoradmin/vector-admin/backend/node_modules/@prisma/engines: Command failed.
 Exit code: 1 
Command: node scripts/postinstall.js 
Arguments: 
Directory: /mnt/c/Development/Projects/Python/vectoradmin/vector-admin/backend/node_modules/@prisma/engines 
Output: 
/mnt/c/Development/Projects/Python/vectoradmin/vector-admin/backend/node_modules/@prisma/engines/dist/scripts/postinstal l.js:22549
         return this[INTERNAL2].defaultPort ?? (this.protocol === "https:" ? 443 : 80); 

SyntaxError: Unexpected token '?'
     at wrapSafe (internal/modules/cjs/loader.js:915:16)
     at Module._compile (internal/modules/cjs/loader.js:963:27) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
     at Module.load (internal/modules/cjs/loader.js:863:32) 
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
     at Module.require (internal/modules/cjs/loader.js:887:19)
     at require (internal/modules/cjs/helpers.js:74:18)
     at Object.<anonymous> (/mnt/c/Development/Projects/Python/vectoradmin/vector-admin/backend/node_modules/@prisma/engi

Any ideas?  

Most cordially, 
Jack Stewart

**Comment by timothycarambat** [comment]
Hey Jack,

Definitely don't ignore engine as the some libraries (and code!) rely on the node 18+ APIs that wont be present in previous versions.

install at _least_ Node 18.0.0 but I recommend 18.13.0. On Ubuntu Jammy you can install node+yarn using the following series of commands:
```
  mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && \
    apt-get install -yq --no-install-recommends nodejs && \
    curl -LO https://github.com/yarnpkg/yarn/releases/download/v1.22.19/yarn_1.22.19_all.deb \
        && dpkg -i yarn_1.22.19_all.deb \
        && rm yarn_1.22.19_all.deb
```

Once those are installed `cd` into the project and run `yarn dev:setup` again and it will install dependencies and copy ENV files to where they need to be for minimal setup!

**Comment by mjackstewart** [comment]
Howdy, Timothy!

Thank you SO much--you're a BRO! I was looking for a vector database
administration application, and I just happened on your video. It was GREAT!

I'm curious: Was there actually a problem that you fixed, or was if
operator error (me)?

Most cordially,
Jack


Jack Stewart (he/him/his)
(812) 786-2439

**Comment by timothycarambat** [comment]
It was just an operator error this time :)

The issue was just using an old version of node that is incompatible with the code for this project!
